<?php

return [
    'fast_menu_enabled' => true,
    'fast_cache_cleaner_enabled' => true,
    'fast_cache_clear_log_enabled' => false,
    'entomai_plugins_menu_enabled' => true,
    'ecommerce_header_menu_enabled' => true,
    'ecommerce_notifications_enabled' => true,
    'contact_notifications_enabled' => true,
    'payment_notifications_enabled' => true,
    'ecommerce_notification_statuses' => ['pending'],
    'contact_notification_statuses' => ['unread'],
    'payment_notification_statuses' => ['pending'],
    'hotel_booking_notification_statuses' => ['pending'],
    'update_header_widget_enabled' => true,
    'sticky_header_enabled' => true,
    'compact_brand_enabled' => true,
    'remove_logo_enabled' => false,
    'brand_custom_text' => '',
    'hide_view_website_button' => false,
    'hide_global_search' => false,
    'hide_botble_notification' => false,
    'admin_appearance_per_user_enabled' => false,
    'hidden_header_hook_items' => [],
    'header_hook_item_catalog' => [],
];
